version: '3.8'

services:
  db:
    image: mariadb:10.9
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root_passwd
      - MARIADB_DATABASE=n8n_db
      - MARIADB_USER=n8n
      - MARIADB_PASSWORD=n8n_passwd
      - MARIADB_MYSQL_LOCALHOST_USER=true
    volumes:
      - ./n8n-db:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=n8n --password=n8n_passwd --execute 'SELECT 1;'"
      interval: 10s
      timeout: 5s
      retries: 10
      
  n8n:
    image: n8n-pyvenv-manager:latest
    restart: always
    environment:
      - DB_TYPE=mariadb
      - DB_MYSQLDB_HOST=db
      - DB_MYSQLDB_DATABASE=n8n_db
      - DB_MYSQLDB_USER=n8n
      - DB_MYSQLDB_PASSWORD=n8n_passwd
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=root
      - N8N_BASIC_AUTH_PASSWORD=change_me
    ports:
      - 5678:5678
      - 1339:139
      - 4445:445
    links:
      - db
    volumes:
      - ./n8n-data:/data
      - ./n8n-node:/home/node
    depends_on:
      db:
        condition: service_healthy